# Summmary

The Northeast U.S. is home to several economically important commercial fisheries, representing a variety of gear types. Vessels on this site are grouped by fishery and gear based on their highest source of revenue during calendar year 2022. Only vessels that provided a complete response to the Greater Atlantic Region Commercial Fishing Business Cost Survey for 2022 are included. See Chapter 3.1 for the definition of a complete survey response. All fisheries and gears are represented in Chapters 5-8 as allowed by data confidentiality rules (at least 3 vessels). Below is a brief summary of the results presented in Chapters 5-8. See Chapter 10 for ways in which these results can be used as well as data limitations.

Chapter 5 provides a summary of fleet ex-vessel revenues. These values are queried from the Catch Accounting and Monitoring System (CAMS), a collaborative database developed by the Greater Atlantic Regional Fisheries Office (GARFO) and the Northeast Fisheries Science Center (NEFSC). Mean and median values show substantially higher vessel revenues for some gear groups (e.g. scallop dredge, trawl) than others (e.g. gillnet, handgear). Similarly, some fisheries (e.g. scallop, squid, mackerel, and butterfish) show substantially higher mean and median vessel revenues than others (e.g. fluke, black sea bass, and scup, lobster).

Chapter 6 provides a summary of costs, which mainly are derived from the 2022 cost survey. A breakdown of costs into major categories shows important insight into the differences between fisheries and gear groups. For example, crew-intensive fisheries such as groundfish, scallop, and squid, mackerel, and butterfish show 41-47% of total costs being payments to crew and 9-22% being trip expenses. In contrast, lobster shows 26% of total costs as payments to crew 31% of total costs as trip expenses. Important similarities are present as well. For example, overhead costs represent between 6-10% of total costs for nearly all fisheries and gear groups.

Operating profit is presented in Chapter 7. This metric is calculated by taking gross revenues (Chapter 5) and subtracting trip expenses and crew payments, highlighted in Chapter 6. Operating profit is an important measure of the short-run economic viability of fishing businesses. If vessels can not cover their operating expenses, fishing trips are not profitable. All gear groups show positive mean and median operating profits, though a small number of observations are negative. These may be explained by vessels participating in other activities outside of commercial fishing in which costs are incurred but revenue is not generated.

Finally, total profit is presented in Chapter 8. This metric is calculated by taking gross revenues (Chapter 5) and subtracting all costs (Chapter 6). Total profit provides important insight into the overall economic viability of fishing businesses. The results show vessels which generated the majority of revenue from scallop or squid, mackerel, butterfish fisheries during 2022 yielded the highest total profits on a mean or median basis. Several fisheries and gear groups show negative mean or median vessel profits. Negative profit during 2022 can be driven by a variety of factors, including high costs, low revenue, as well as vessel activity that incurs costs but does not generate revenue (e.g. leisure uses on a commercial fishing vessel). 


# Discussion

## Applications
These profit profiles are intended to support the management of commercial fisheries in the Northeast U.S. The results presented have a number of different applications, including:

  1. Cost distributions and cost share overviews across fishing fleets
    a. Allowing end-users to gain a foundational understanding of cost distributions and shares by fishing fleet. In economic analyses to support management, operating profit/net revenue is most often calculated. Across FMPs, operating costs account for varying levels of total costs. 
  2. Profits by fishing fleet 
    a. Allowing end-users to gain a better understanding of how gross revenues translate to profit by fishing fleet. 
  3. Supporting research into the viability of fishing operations. By examining the economic health of commercial vessels, the implications of management actions on fisheries can be better understood. These potential actions include, but are not limited to:
    a. Changes in fishing quotas/days-at-sea 
    b. Re-allocation of quota among sectors (e.g. commercial vs. recreational)
    c. Establishment or modification of accumulation limits
    d. Changes in costs faced by fishing vessels (e.g. monitoring)

These data and analyses offer the best available information on the following topics at the fleet level:
  - Profit estimations
  - Cost profiles and shares
  - Operating profit estimations 
  - Crew and captain payments 

Until additional cost data is collected, processed and analyzed or cost models have been conducted, these estimates are recommended for generating baseline analyses. 

Given these analyses, we recommend using these data for analyses and summaries such as:
  - Affected Environments in frameworks and amendments
  - Economic analyses investigating impacts or changes to fishing costs
  - Impacts of changes in estimated landings on profits


For management purposes, these 2022 snapshots can be incorporated into the Affected Environment: Human Communities section for various FMP actions. This section has frequently focused on trends in gross revenue and fishery effort. Profit provides additional information in capturing the economic performance of the fishery. 

The profiles can also be incorporated into the economic impact analysis of management actions. For example, the ratio of total profits to gross revenues can inform how changes in quota/expected landings impact the bottom line of vessel operators. For the squid, mackerel, butterfish fishery, the ratio of total profit/gross revenue is 33% when using mean values and 26% using median values. For the scallop fishery, these numbers are 32% and 17% respectively. For the groundfish fishery, these numbers are 26% and 8%.

```{r, echo=FALSE}
library(dplyr)

gear_margins<- read.csv(file="V:/Ardini_Cost_Survey/SAS_Cost_Survey/Profitability_Profiles/Calculate_Profit/Final/profit_summary/gear_profit_margin.csv")
gear_margins_2 <- gear_margins %>% mutate(Median_Revenue = prettyNum(med_rev, big.mark = ',', scientific = FALSE))
gear_margins_3 <- gear_margins_2 %>% mutate(Median_OP = prettyNum(med_op, big.mark = ',', scientific = FALSE))
gear_margins_4 <- gear_margins_3 %>% mutate(Median_TP = prettyNum(med_tp, big.mark = ',', scientific = FALSE))
gear_margins_4$Median_Revenue<-paste("$",gear_margins_4$Median_Revenue)
gear_margins_4$Median_OP<-paste("$",gear_margins_4$Median_OP)
gear_margins_4$Median_TP<-paste("$",gear_margins_4$Median_TP)
gear_margins_4$op_margin<-paste(gear_margins_4$op_margin,"%")
gear_margins_4$tp_margin<-paste(gear_margins_4$tp_margin,"%")
gear_margins_5 <- subset(gear_margins_4, select=c(Gear, Median_Revenue, Median_OP, Median_TP, op_margin, tp_margin))
knitr::kable(gear_margins_5)

fmp_margins<- read.csv(file="V:/Ardini_Cost_Survey/SAS_Cost_Survey/Profitability_Profiles/Calculate_Profit/Final/profit_summary/fmp_profit_margin.csv")
fmp_margins_2 <- fmp_margins %>% mutate(Median_Revenue = prettyNum(med_rev, big.mark = ',', scientific = FALSE))
fmp_margins_3 <- fmp_margins_2 %>% mutate(Median_OP = prettyNum(med_op, big.mark = ',', scientific = FALSE))
fmp_margins_4 <- fmp_margins_3 %>% mutate(Median_TP = prettyNum(med_tp, big.mark = ',', scientific = FALSE))
fmp_margins_4$Median_Revenue<-paste("$",fmp_margins_4$Median_Revenue)
fmp_margins_4$Median_OP<-paste("$",fmp_margins_4$Median_OP)
fmp_margins_4$Median_TP<-paste("$",fmp_margins_4$Median_TP)
fmp_margins_4$op_margin<-paste(fmp_margins_4$op_margin,"%")
fmp_margins_4$tp_margin<-paste(fmp_margins_4$tp_margin,"%")
fmp_margins_5 <- subset(fmp_margins_4, select=c(Fishery, Median_Revenue, Median_OP, Median_TP, op_margin, tp_margin))
knitr::kable(fmp_margins_5)

gear_fmp_margins<- read.csv(file="V:/Ardini_Cost_Survey/SAS_Cost_Survey/Profitability_Profiles/Calculate_Profit/Final/profit_summary/gear_fmp_profit_margin.csv")
gear_fmp_margins_2 <- gear_fmp_margins %>% mutate(Median_Revenue = prettyNum(med_rev, big.mark = ',', scientific = FALSE))
gear_fmp_margins_3 <- gear_fmp_margins_2 %>% mutate(Median_OP = prettyNum(med_op, big.mark = ',', scientific = FALSE))
gear_fmp_margins_4 <- gear_fmp_margins_3 %>% mutate(Median_TP = prettyNum(med_tp, big.mark = ',', scientific = FALSE))
gear_fmp_margins_4$Median_Revenue<-paste("$",gear_fmp_margins_4$Median_Revenue)
gear_fmp_margins_4$Median_OP<-paste("$",gear_fmp_margins_4$Median_OP)
gear_fmp_margins_4$Median_TP<-paste("$",gear_fmp_margins_4$Median_TP)
gear_fmp_margins_4$op_margin<-paste(gear_fmp_margins_4$op_margin,"%")
gear_fmp_margins_4$tp_margin<-paste(gear_fmp_margins_4$tp_margin,"%")
gear_fmp_margins_5 <- subset(gear_fmp_margins_4, select=c(Gear_Fishery, Median_Revenue, Median_OP, Median_TP, op_margin, tp_margin))
knitr::kable(gear_fmp_margins_5)

```

## Limitations and Future Work
There are a number of limitations and caveats to consider when to use the data provided on this site. The Commercial Fishing Business Cost Survey is conducted within the Northeast region every few years, such that this does not provide annual-level estimations or contiguous time series data. For some vessel owners, 2022 may have been an unusually profitable year, either through increased revenues, decreased costs, or a combination. In contrast, other vessels likely experienced a less profitable year than normal in 2022. A vessel owner may have been more/less likely to respond based on their economic situation during 2022. It is difficult to assess this effect since the individuals that respond to the survey vary over time and the survey is not conducted annually. When using the information, special attention should be placed on the number of respondents and the response rate associated with each gear or fishery group. Though efforts are ongoing to understand the representativeness of the data, there can still be caveats at the unit of observation (i.e., gear and species level may be sparse for creating fleet-wide inferences). There is currently no way to estimate the costs across survey non-respondent such that means are the only method of estimating costs for vessels outside the snapshots. This can cause issues in applying a mean to a single vessel as results vary greatly from vessel to vessel.  As more years of data become available,we can enhance our understanding of the economic performance of fishing fleets in the region. Data collected in future surveys will feed into the profit calculations presented on this site. Similar to the gear/FMP dropdown function, the user will be able to query the year of interest.


# References

Ardini G., Murphy T., Werner S., Bailey M. 2022. An Overview of the Social Sciences Branch (SSB) Commercial Fishing Business Cost Survey in the Northeast: Protocol and Results for Survey Years 2011, 2012, and 2015. US Dept Commer, Northeast Fish Sci Cent Tech Memo 278. 146 p.

Das C. 2013. An Overview of the Annual Cost Survey Protocol and Results in the Northeast (2007 to 2009). US Dept Commer, Northeast Fish Sci Cent Tech Memo 226. 45 p.

Kitts, A., Van Anrooy, R., Van Eijs, S., Pino Shibata, J., Pallalever Pérez, R., Augusto Gonçalves, A., Ardini, G., Liese, C., Pan, M., Steiner, E. 2020. Techno-economic performance review of selected fishing fleets in North and South America. FAO Fisheries and Aquaculture Technical Paper No. 653/2. Rome, FAO.

Kitts A., Walden J., Squires D., Travis M., Steiner E., Pfeiffer L., Liese C., Pan M. 2022. NOAA Fisheries Best Practices for Measuring Returns to Fishing Businesses. US Dept Commer, NOAA Tech Memo NMFS-F/SPO-231, 54 p.

(forthcoming) Werner S., Conley E., Ardini G. 2025. Greater Atlantic Region Commercial Fishing Business Cost Survey for 2022: Survey Implementation, Data Processing Methods and Preliminary Results.
