# Summmary
The Northeast U.S. is home to several economically important commercial fisheries, representing a variety of gear types. Vessels on this site are grouped by fishery and gear-type based on their highest source of revenue during calendar year 2022. Only vessels that provided a complete response to the Greater Atlantic Region Commercial Fishing Business Cost Survey for 2022 are included (see Chapter 3.1 for the definition of a complete survey response). All fisheries and gears are represented in Chapters 5-8 as allowed by data confidentiality rules (at least 3 vessels). Below is a brief summary of the results presented in Chapters 5-8. See Chapter 10 for ways in which these results can be used as well as data limitations.

Chapter 5 provides a summary of fleet ex-vessel revenues. These values are queried from the Catch Accounting and Monitoring System (CAMS), a collaborative database developed by the Greater Atlantic Regional Fisheries Office (GARFO) and the Northeast Fisheries Science Center (NEFSC). Mean and median values from responding vessels show substantially higher vessel-level revenues for some gear groups (e.g. scallop dredge, trawl) than others (e.g. gillnet, handgear). These revenue trends are similar to those observed across the entire survey sampling frame. Similarly, some fisheries (e.g. scallop, squid, mackerel, and butterfish) show substantially higher mean and median vessel revenues than others (e.g. fluke, black sea bass, and scup, lobster).

Chapter 6 provides a summary of costs, which mainly are derived from the 2022 cost survey. A breakdown of costs into major categories shows important insight into the differences between fisheries and gear groups. For example, crew-intensive fisheries such as groundfish, scallop, and squid, mackerel, and butterfish show 41-47% of total costs being payments to crew and 9-22% being trip expenses. In contrast, lobster shows 26% of total costs as payments to crew 31% of total costs as trip expenses. Important similarities are present as well. For example, overhead costs represent between 6-10% of total costs for nearly all fisheries and gear groups.

Operating profit is presented in Chapter 7. This metric is calculated by taking gross revenues (Chapter 5) and subtracting trip expenses and crew payments (Chapter 6). Operating profit is an important measure of the short-run economic viability of fishing businesses. If vessels can not cover their operating expenses, fishing trips are not profitable and are theoretically better off shutting down to avoid further losses. All gear groups show positive mean and median operating profits which is expected, though a small number of observations are negative. These may be explained by vessels participating in other activities outside of commercial fishing in which costs are incurred but revenue is not generated. 

Total profit is presented in Chapter 8. This metric is calculated by taking gross revenues (Chapter 5) and subtracting all costs (Chapter 6). Total profit provides important insight into the overall economic viability of fishing businesses. The results show vessels which generated the majority of revenue from scallop or squid, mackerel, butterfish fisheries during 2022 yielded the highest total profits on a mean or median basis. Several fleets show negative mean or median vessel profits by gear group (gillnet, handgear, longline) and fishery (dogfish, herring, HMS, monkfish, striped bass). Negative profit during 2022 can be driven by a variety of factors, including high costs, low revenue, as well as vessel activity that incurs costs but does not generate revenue (e.g. leisure uses of a commercial fishing vessel). Since we are unable to determine the most significant drivers of negative vessel profits during 2022, assessing the overall viability of fishing businesses from one year of data is challenging. However, these results do provide insight into which fishing fleets show greater/lesser economic viability during 2022.   

Finally, profit margins are presented in Chapter 9. Operating profit margins are calculated by taking median operating profit (Chapter 7) and dividing by gross revenues (Chapter 5). Total profit margins are calculated by taking median total profit (Chapter 8) and dividing by gross revenues (Chapter 5). Operating profit margins by gear range from 25-46% and by fishery generally ranged between 20-50%. Total profit margins show the highest grossing fisheries (scallop and squid, mackerel, butterfish) also have the highest margins. Most other fisheries show margins slightly positive or slightly negative.


# Discussion

## Applications
These profit profiles are intended to support the management of commercial fisheries in the Northeast U.S. These data and analyses offer a number of different applications, including:

1. Cost summaries* and shares
2. Operating and total profit estimates
3. Profits margins

*Additional years of data exist on the [Cost Data Visualization Tool](https://apps-nefsc.fisheries.noaa.gov/cost-data/) for these categories

1. Cost summaries and shares
    a. These summaries allow end-users to gain a foundational understanding of costs incurred and shares by fishing fleet which can be used in economic analyses to support management, operating profit/net revenue is most often calculated. Across FMPs, operating costs account for varying levels of total costs. It can also demonstrate the impact of policies if they are expected to increase a specific cost category.
2. Operating and total profit estimates
    a. Information on total payments to crew provide an additional component to operating profit
    b. Operating profits are currently estimated using cost information collected by at-sea observers
    c. Total profits have not previously been estimated for Northeast region commercial fisheries
3. Profits margins
    a. Allow end-users to gain a better understanding of how gross revenues translate to operating profit and total profit by fishing fleet. 
    b. Profit margins calculations can support research into the viability of fishing operations. 

Given these analyses, we recommend using these data for analyses and summaries for management frameworks and amendments. Information from this site can be used within the following management action sections 

1. Affected Environment: Human Communities 
    a. This section has frequently focused on trends in gross revenue and fishery effort. Profit provides additional information in capturing the recent economic performance of the fishery. 
2. NEPA: Economic Impacts
3. Executive Order 12866
    
By examining the economic health of commercial vessels, the implications of management actions on fisheries can be better understood. For example, profit margins provide a baseline understanding of how changes in estimated landings translate to profits. Cost shares provide an overview of which costs are more/less substantial by fishing fleet. Potential management actions include, but are not limited to:

1. Changes in fishing quotas/days-at-sea 
2. Re-allocation of quota among sectors (e.g. commercial vs. recreational)
3. Establishment or modification of accumulation limits
4. Changes in costs faced by fishing vessels (e.g. monitoring)

Until additional cost data is collected, processed and analyzed or cost models have been conducted, these estimates are recommended for generating baseline analyses. 

## Data Limitations and Future Work
Though many of these metrics presented on this site are suggested to be used given they are the best information available, there are a number of important data limitations and caveats. First, the Commercial Fishing Business Cost Survey is conducted within the Northeast region every few years, such that a contiguous data time series is not feasible. For some vessel owners, 2022 may have been an unusually profitable year, either through increased revenues, decreased costs, or a combination. In contrast, other vessels likely experienced a less profitable year than normal in 2022. A vessel owner may have been more/less likely to respond based on their economic situation during 2022. It is difficult to assess this effect since the individuals that respond to the survey vary over time and the survey is not conducted annually. Second, a couple of survey cost questions do not directly translate to the income statement presented in Kitts et al. (2022). Mainly, vessel repairs/maintenance cannot be separated from vessel improvements and the principal paid on loans cannot be separated from the interest paid. The results presented include combined repair/maintenance and upgrade/improvement potentially biasing profits low. The amount paid on loans is not included, potentially biasing profits high. Third, when using information from this site, attention should be placed on the number of respondents and the response rate associated with each gear or fishery group. Though efforts are ongoing to understand the representativeness of the data, there can still be caveats at the unit of observation (i.e., gear and species level may be sparse for creating fleet-wide inferences). Fourth, end users should be aware of other fishery metric data sources. For example, while revenue data is provided for all vessels highlighted on this site, revenue information for all commercial fishing vessels in the Northeast is readily available to all NOAA Fisheries staff in the region. For industry members and other interested stakeholders outside of NOAA Fisheries, the [NEFSC Performance Measures site](https://apps-nefsc.fisheries.noaa.gov/pm/index.php/programs/2) provides average revenue by vessel as well. Lastly, as a general caveat, there is currently no model to estimate the costs across survey non-respondent such that means and weighting are the only method of estimating costs for vessels outside the snapshots. This can cause issues in applying a mean to a single vessel as results vary greatly from vessel to vessel.  

In terms of future developments, as more years of data become available, we can enhance our understanding of the economic performance of fishing fleets in the region. As time and resources permits, future survey data will feed into the profit calculations presented on this site. Similar to the gear/FMP dropdown function, the end-user will be able to query the year of interest.


# References

Ardini G., Murphy T., Werner S., Bailey M. 2022. An Overview of the Social Sciences Branch (SSB) Commercial Fishing Business Cost Survey in the Northeast: Protocol and Results for Survey Years 2011, 2012, and 2015. US Dept Commer, Northeast Fish Sci Cent Tech Memo 278. 146 p.

Das C. 2013. An Overview of the Annual Cost Survey Protocol and Results in the Northeast (2007 to 2009). US Dept Commer, Northeast Fish Sci Cent Tech Memo 226. 45 p.

Kitts, A., Van Anrooy, R., Van Eijs, S., Pino Shibata, J., Pallalever Pérez, R., Augusto Gonçalves, A., Ardini, G., Liese, C., Pan, M., Steiner, E. 2020. Techno-economic performance review of selected fishing fleets in North and South America. FAO Fisheries and Aquaculture Technical Paper No. 653/2. Rome, FAO.

Kitts A., Walden J., Squires D., Travis M., Steiner E., Pfeiffer L., Liese C., Pan M. 2022. NOAA Fisheries Best Practices for Measuring Returns to Fishing Businesses. US Dept Commer, NOAA Tech Memo NMFS-F/SPO-231, 54 p.

National Marine Fisheries Service. 2024. Fisheries Economics of the United States, 2021. U.S. Dept. of Commerce, NOAA Tech. Memo. NMFS-F/SPO-247, 188 p.

(forthcoming) Werner S., Conley E., Ardini G. 2025. Greater Atlantic Region Commercial Fishing Business Cost Survey for 2022: Survey Implementation, Data Processing Methods and Preliminary Results.