# Introduction
Profit is an important metric in assessing the economic performance of commercial fishing fleets and in evaluating the impacts of proposed regulations. Evaluation of economic impacts is required under a number of laws, including Including the Magnuson-Stevens Fishery Conservation and Management Act (MSA), the National Environmental Policy Act (NEPA), Executive Order 12866, and the Regulatory Flexibility Act (RFA). 

Within the Northeast United States, commercial revenues are readily available to NOAA Fisheries, as all federally permitted vessels are required to report sales to licensed dealers. Cost data, on the other hand, have generally been the limiting factor in calculating vessel profits. The Northeast Fisheries Science Center conducts a voluntary survey to collect comprehensive cost information from commercial fishing vessel owners. This survey was last implemented during 2023 for costs incurred during calendar year 2022. One of the primary goals of the survey was to calculate vessel-level profits. 

Using data primarily collected from the most recent cost survey, this site presents commercial fishing vessel profits during 2022 for those vessels who participated in the survey effort. All information presented follows data confidentiality rules as required under the MSA (at least 3 vessels must be present in each summary group). These snapshots will serve as a performance metric in evaluating the economic impacts of proposed fishery management actions. 

## Cost Survey Background
Starting in 2007, the Social Sciences Branch (SSB) of the Northeast Fisheries Science Center (NEFSC) has intermittently collected commercial fishing cost information from vessel owners through a voluntary survey. The most recent survey, formally known as the Greater Atlantic Region Commercial Fishing Business Cost Survey for 2022 (hereafter 2022 cost survey), was fielded in March-August 2023 to collect costs incurred by vessel owners during calendar year 2022. The 2022 cost survey was split up into the following sections:

  1. General Information
  2. New/Replacement, Repair/Maintenance, and Upgrade Costs for the Selected Vessel
  3. Vessel Costs for the Selected Vessel
  4. Trip Expenses for the Selected Vessel
  5. Crew Payment System for the Selected Vessel
  6. Overhead Costs
  7. The Value of the Selected Vessel
  8. Quota Costs and Revenues for the Selected Vessel
  9. Completeness of Cost Information
  10. Survey Follow-up Questions

Each owner of a federally permitted commercial fishing vessel that was active in either calendar year 2021 or 2022 received a survey. A total of 2,495 individuals were sent the 2022 cost survey with 422 surveys returned. After accounting for incomplete returned surveys and ineligibles within the sampling frame, the final response rate was 14.8% (367/2,477). For further details on the implementation of the 2022 cost survey see Werner et al. (in review). For more information on early iterations of the cost survey, see Das (2015) and Ardini et al. (2022). An overview of survey data collected, as well as applications for cost data, can be found on the [Cost Survey Landing Page](https://www.fisheries.noaa.gov/new-england-mid-atlantic/commercial-fishing/commercial-fishing-business-cost-survey). Additionally, the [Cost Data Visualization Tool](https://apps-nefsc.fisheries.noaa.gov/cost-data/) presents distributions for the various costs provided by survey respondents.


# Metrics
There are a number of different metrics to measure net returns to commercial fishing businesses as detailed in Kitts et al. (2022). For example a cash flow statement typically shows returns over time and can help inform the need to acquire cash reserves through loans. An income statement is somewhat similar to a cash flow statement and focuses on gross revenues and costs associated with operating a fishing business. An economic profit statement includes opportunity costs, such as physical capital costs and the vessel owner’s time. A vessel may yield a positive accounting profit but a negative economic profit after accounting for opportunity costs.

This page provides modified income statements with a few changes from the methods outlined in Kitts et al. (2022). For revenues, the only alteration in methods is the exclusion of direct subsidies, as this information is not available. For costs, there are a few categories not included, also due to a lack of available information. These categories include taxes (both ad Valorem and income), interest expenses (due to interest not being separable from principal), and gain/loss on the sale of capital assets. Using available revenues and costs, this page examines both operating profit and total profit. Operating profit can help inform the immediate viability of a fishing business- if trip expenses cannot be covered, economic theory suggests that the vessel will cease operations. Total profit measured over an extended time period informs the long-term viability of a fishing business. Measured for 2022, this metric can be used to calculate profit margin, the ratio of profit to gross revenues. However, a negative total profit for 2022 does not necessarily translate into a fishing business that is not viable as some costs, such as vessel repairs, are expected to fluctuate from year to year.

## Operating Profits
Operating profit refers to gross revenues minus operating costs (variable costs). Within the 2022 cost survey, two sections in particular cover operating costs. The trip expenses section (#4) collects information on fuel, bait, ice, and food. The crew payment section (#5) includes the total amount paid to crew and hired captains, as well as any benefits paid out. Outside of the survey, a few costs collected by at-sea observers, fresh water and crew supplies, are also included in the operating profit calculation.

EQUATION 1: Gross Revenue - (Trip Expenses + Crew Payments)

## Total Profits
Total profit refers to operating profit minus non-operating costs (fixed and quasi-fixed costs). Within the 2022 cost survey, a few different sections include non-operating costs. The vessel repairs and, upgrades section (#2) includes the amount spent on various vessel components including the engine, hull, fishing gear, electronics, and safety equipment. The vessel costs section (#3) factors in mooring fees, permit fees, and vessel insurance. The overhead section (#6) includes, among other costs, business vehicle expenses, association fees, non-crew labor payments, and office/storage expenses. The quota costs and revenue section (#8) is also included as a component of non-operating costs. Lastly, depreciation is estimated from the vessel values section (#7).

EQUATION 2: Operating Profit - (RMUI/other + Vessel Costs  + Overhead + Quota Leasing + Depreciation)


# Respondent Pool
A total of 422 surveys were returned to the Social Sciences Branch at the conclusion of the 2022 cost survey. Profit calculations were first performed for all observations followed by a series of steps to eliminate those observations that were deemed inappropriate to include.

## Filtering of Observations
The first filtering step specified that all surveys must have answered at least one cost-related question. This step eliminated 55 observations, bringing the total number to 367. The second filtering step specified that the responding vessel must be commercially active (revenues >$0) during 2022. A further 46 observations were dropped, bringing the total to 321.

Following completion of the initial filtering, a few other steps were performed. The 2022 cost survey included the ten sections listed under Cost Survey Background. For each response, the number of survey sections skipped were counted, where a skipped section was any case in which all questions within the section were left blank. For this exercise, five survey sections were evaluated. If a survey skipped multiple sections, it was removed from the dataset. A total of 17 observations skipped multiple survey sections, bringing the total to 304. An additional 12 observations out of the remaining 304 skipped one survey section. These cases were further evaluated to look at the specific section skipped. Four out of the 12 only skipped the crew payment section. Since these were all small vessels with relatively low costs and operating profit, assuming there was no crew on board was deemed appropriate. The other 8 observations that skipped one survey section were dropped. An additional 14 observations that belonged to a fishery with fewer than three observations were dropped. Finally, 1 additional observation was dropped due to extreme costs in a number of different categories, resulting in a final dataset of 281 observations. Out of a possible 31 questions answered, these observations provided responses to 28 questions on average, with a range of 20-31 questions answered. 


# Profit Calculation Methods

## Commercial Revenue
All individuals that were sampled for the 2022 cost survey were owners of federally-permitted commercial fishing vessels active in 2021 or 2022. Federally-permitted vessels are required to sell their catch to federally-licensed seafood dealers and commercial revenue is derived from harvested catch on commercial trips sold to a licensed dealer. All vessels included in the profit snapshots generated commercial fishing revenue >$0 during 2022 from landings occurring in the Northeast region (ME to Cape Hatteras, NC). Of note, the reporting requirements for landings of bluefin tuna differ from other species landed in the Northeast region. Bluefin tuna revenue was queried from the Atlantic Coastal Cooperative Statistics Program (ACCSP) data warehouse, while all other species revenue was queried from the Catch Accounting and Management System (CAMS) housed at the Greater Atlantic Regional Fisheries Office (GARFO) and the NEFSC.

### Primary Gear
Vessel primary gear is defined according to the largest contributor to total commercial vessel revenue during 2022. Fishing gears, primarily from Vessel Trip Reports (VTRs) were grouped into the same categories as used for the 2022 cost survey sampling frame. For example, bottom trawl and midwater trawl were grouped into a broader trawl category. The resulting primary gear groups are as follows: gillnet, handgear, hydraulic dredge, longline, pot/trap, scallop dredge, seine, trawl, and unknown. Due to low response levels for some primary gear groups, results are unable to be presented.

### Primary Fishery
Vessel primary fishery is also defined as the largest contributor to total commercial vessel revenue during 2022. Species were grouped into Fishery Management Plans (FMPs) as managed by the New England and Mid-Atlantic Fishery Management Councils, as well as American lobster, managed by the Atlantic States Marine Fisheries Commission. A few other fisheries (channeled whelk, highly migratory species, striped bass) are also included due to sufficient response. Other fisheries received low response levels and results are unable to be presented.

### Primary Gear/Fishery
Vessel primary gear (4.1.1) and primary fishery (4.1.2) were also combined to examine differences within more specific fleets. For most gear types, multiple fisheries are represented. However, scallop dredge gear, for example, is represented by only one fishery (sea scallop). Due to low response levels for some primary gear/fisheries, results are unable to be presented.

## For-Hire Revenue
While the 2022 cost survey was sent to vessels engaged in commercial fishing during 2021 or 2022, some of these vessels also were engaged in for-hire fishing. In order to accurately capture vessel-level profits, it is important to include this additional source of revenue. For-hire revenue is derived from angler/customer payments on recreational trips.

All 2022 party/charter trips, and the number of anglers per trip, were first pulled from logbook data. Average angler charter/guide fees by state were then retrieved from the results of the [2022 National Angler Expenditure Survey](https://www.fisheries.noaa.gov/national/socioeconomics/marine-recreational-fishing-expenditure-survey) administered by NOAA Fisheries. This survey is conducted every 3-5 years to better understand the economic contribution of recreational fishing within each region. The survey collects information on a variety of angler expenditures including bait, ice, lodging, and travel costs. For the purpose of the vessel profit calculation, only the amount paid by the angler for the party/charter ticket is used. State-level averages from the angler expenditure survey were used in light of the variability in fees by state within the Northeast region as well as the high level of response for each state. The average angler fee was multiplied by the number of anglers for each 2022 party/charter trip by state. Finally, the trip-level calculations were summed to an annual vessel-level value.

## Survey Costs
The vast majority of cost information used in the calculation of vessel profits came directly from the 2022 cost survey. Survey data was used from the following categories within sections highlighted in Chapter 1.1 Cost Survey Background:

1. New/Replacement, Repair/Maintenance, and Upgrade Costs for the Selected Vessel
    a. Propulsion Engine
    b. Seine Skiff (Seine survey version only)
    c. Deck Equipment / Other Machinery
    d. Haul-out Costs
    e. Hull
    f. Fishing Gear
    g. Wheelhouse Electronics
    h. Processing / Refrigeration
    i. Safety Equipment
2. Vessel Costs for the Selected Vessel
    a. Mooring/Docking Fees
    b. IFQ Cost Recovery Fees (Scallop Dredge survey version only)
    c. State and Federal Permits and/or License Renewal Fees
    d. Launch and Trailer Fees (Handgear survey version only)
    e. Annual Vessel Insurance Premium
3. Trip Expenses for the Selected Vessel
    a. Fuel 
    b. Bait
    c. Food for captain and crew
    d. Ice
    e. Catch Handling- costs for auction, lumping, grading, shipping/trucking, and unloading. 
    f. At-sea Processing At-sea Boxing/Packaging
    g. Paralytic Shellfish Poison Testing (Hydraulic Dredge survey version only)
4. Crew Payment System for the Selected Vessel
    a. Total Payments to Crew
    b. Total Payments to Hired Captain
    c. Benefits Paid to Crew and/or Hired Captain
5. Overhead Costs
    a. Business Vehicle Costs
    b. Business Travel Costs
    c. Association Fees 
    d. Legal Expenses 
    e. Additional Labor Payments
    f. Advertising Costs
    g. Communication Costs
    h. Office/Workshop/Storage Expenses
    i. Spotter Planes, Drones or Other Aerial Search Expenses (Seine survey version only)
6. Quota Costs and Revenues for the Selected Vessel
    a. Quota Leasing Costs
    b. Quota Leasing Revenue
    c. Quota Monitoring Costs
7. Completeness of Cost Information
    a. Other Costs for the Selected Vessel

From these various cost categories within the survey, some data manipulation was required to make costs usable at the vessel/annual level. These data manipulation steps are summarized below.

Trip Expenses: Survey respondents were given the option of providing trip expenses either at the annual level or as a trip average. For those respondents who filled in the average cost per trip, the value was multiplied by the number of commercial trips taken during 2022. In general, the number of trips was used directly from the survey (Q2). In cases where this information was not filled in, the number of trips was retrieved from VTRs and/or dealer reports. Trip expenses were then allocated to the vessel owner based on how the survey respondent indicated these expenses were paid (Q6). If the respondent answered that the crew paid for trip expenses, the assigned cost to the vessel owner was $0. If the respondent answered that the boat/owner paid for trip expenses, 100% of these costs were assigned to the vessel owner. If the respondent answered that trip expenses were shared between boat/owner and crew, these costs were multiplied by the % indicated for the vessel owner to assign these costs.

Overhead Costs: Survey respondents were given the option of providing these costs either at the vessel level or at the business level. For those respondents who filled in business level costs, the value was divided by the number of vessels owned by the respondent during 2022. The number of vessels owned was taken directly from the survey (Q13). 

Quota Costs and Revenues: Survey respondents were given the option to provide quota leasing costs either at the vessel-level or across multiple vessels. If this cost was provided across multiple vessels, the value was divided by the specific number of vessels the quota leasing cost was attributed to (Q17). Similar to trip expenses, quota leasing costs were then allocated to the vessel owner based on how the survey respondent indicated these expenses were paid (Q18). If the respondent answered that the crew paid for trip expenses, the assigned cost to the vessel owner was $0. If the respondent answered that the boat/owner paid for trip expenses, 100% of these costs were assigned to the vessel owner. If the respondent answered that trip expenses were shared between boat/owner and crew, these costs were multiplied by the % indicated for the vessel owner to assign these costs. Quota leasing revenue was then subtracted from costs to calculate net quota leasing costs to the vessel. Quota leasing occurs within the groundfish, sea scallop, surf clam/ocean quahog, and tilefish fisheries. Due to net quota leasing representing a small portion of total costs for the various fleets presented on this site, these costs are not included in the cost distribution summaries found in Chapter 6. However quota net leasing costs are included in total profit profiles found in Chapter 8.

Other Costs: At the end of the survey, respondents were given the opportunity to list other costs that were not included in the survey. When other costs were listed, they were evaluated on a case-by-case basis (see Werner et al. 2025). When deemed possible, other costs listed were allocated to an existing cost category. Those that could not be allocated to an existing cost category were excluded from the profit calculation. Examples of costs that were able to be allocated to an existing category include registration fees were added to Permit Fees and non-descript vessel repairs/maintenance were allocated evenly across the various repair/maintenance categories.

## Additional Trip Costs 
As covered in Chapter 4.3, the 2022 cost survey queried a variety of expenses faced by vessel owners. During pre-testing of the survey instrument, fishing industry members generally felt that the survey did a good job of including all significant costs. Furthermore, comments on the survey itself and a lack of other costs filled in by respondents indicated the survey covered significant costs. However there are two costs, crew supplies and fresh water, that are collected by at-sea observers that were not included in the 2022 cost survey. 

To capture these costs, data from observer programs was used to calculate average costs per trip by gear. All 2022 trips from observer data tables were pulled, along with the primary gear utilized on each trip. The average crew supply and fresh water trip costs by gear type were calculated and these averages were then merged by gear with all of the trips taken by survey responding vessels during 2022. Finally, trip-level costs were summed to the vessel-level.

## Depreciation
The final cost component included in the profit calculation is vessel depreciation. Ideally, a different depreciation value would be assigned to each physical capital component (e.g. electronics, engine, hull) using the estimated market value and age of each piece of vessel equipment. This method would require additional information beyond that collected in the 2022 cost survey. 

Information on the estimated market vessel value, including all equipment and fishing gear, was collected in the 2022 cost survey. However the number of responses to this question were lower than other survey questions explained in part by the inclusion of a “I prefer not to answer” option, which was not included for other survey questions. Given the relative lack of response for vessel market value, an alternate method was used in which shadow values of vessel characteristics including age, gross tonnage, length, and type of construction were estimated. The shadow values were then multiplied by each vessel characteristic to calculate a total vessel value. From the vessel values, a depreciation cost was calculated as 4% of the value for those vessels less than 25 years old and 2% of the value for those vessels 25 years or older following methods utilized for fishing fleets in Kitts et al. (2020).